version: "2.3"

services:

    app:
      image: php:7.4-apache
      ports:
        - "${PORT}:80"
      volumes:
        - .:/srv/pdf.js
        - ./apache2.conf:/etc/apache2/sites-available/000-default.conf
      mem_limit: 80M
      mem_reservation: 6M